language: cpp

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes ppa:canonical-qt5-edgers/qt5-beta2
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake libpulse-dev qtbase5-dev qtdeclarative5-dev libqt5svg5-dev qtmultimedia5-dev libqt5webkit5-dev libsqlite3-dev libsdl2-dev
script:
    - qmake -qt=qt5 -v
    - echo "Building desktop version..."
    - qmake -qt=qt5 Desktop.pro
    - make
    - make clean
    - echo "Building mobile version..."
    - qmake -qt=qt5 Mobile.pro
    - make
    - make clean
