language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libsdl2-dev build-essential
  - sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh

script:
  - qmake QDriverStation.pro
  - make -j4
